#!/usr/bin/python3
def do_update(self, *args):
    """ Update an attribute of a given class."""
    if len(arg) < 1:
     73             print("** class name missing **")
      74             return
       75         else:
        76             name = arg[0]
	 77         if name not in globals() or not isinstance(globals()[name], t\
	     ype):
	      78             print("** class name missing **")
	                  return
	                 if len(arg) < 2:
		             print("** instance id missing **")
		             return